scan_timeout = 30
command_timeout = 500
add_newline = true

[character]
disabled = false
format = '[ﮊ](bold purple) $symbol '
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vicmd_symbol = '[❮](bold green)'

[cmake]
disabled = false
format = 'via [$symbol($version )]($style)'
symbol = '喝'
style = 'bold blue'

[cmd_duration]
disabled = false
min_time = 2000
format = 'took [$duration]($style) '
style = 'yellow bold'
show_milliseconds = false
show_notifications = false
min_time_to_notify = 45000

[directory]
disabled = false
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'cyan bold'
read_only = ' '
read_only_style = 'yellow'
truncation_symbol = ''
home_symbol = '~'

[docker_context]
disabled = false
symbol = ' '
style = 'blue bold'
format = 'via [$symbol$context]($style) '

[env_var]
disabled = false
symbol = ''
style = 'black bold dimmed'
format = 'with [$env_value]($style) '

[git_branch]
disabled = false
format = 'on [$symbol$branch]($style)(:[$remote]($style)) '
symbol = ' '
style = 'bold purple'
truncation_length = 9223372036854775807
truncation_symbol = '…'
only_attached = false
always_show_remote = false

[git_commit]
disabled = false
commit_hash_length = 7
format = '[\($hash$tag\)]($style) '
style = 'green bold'
only_detached = true
tag_symbol = ' '
tag_disabled = true

[git_state]
disabled = false
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
am = 'AM'
am_or_rebase = 'AM/REBASE'
style = 'bold yellow'
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'red bold'
stashed = '\$'
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
conflicted = ''
deleted = ''
renamed = ''
modified = ''
staged = ''
untracked = ''

[hostname]
disabled = false
ssh_only = true
trim_at = '.'
format = '[$hostname]($style) in '
style = 'green dimmed bold'

[jobs]
disabled = false
threshold = 1
format = '[$symbol$number]($style) '
symbol = '✦'
style = 'bold blue'

[lua]
disabled = false
format = 'via [$symbol($version )]($style)'
symbol = ' '
style = 'bold blue'
lua_binary = 'lua'
detect_extensions = ['lua']
detect_files = ['.lua-version']
detect_folders = ['lua']

[memory_usage]
disabled = true
threshold = 75
format = 'via $symbol[$ram( | $swap)]($style) '
style = 'white bold dimmed'
symbol = ''

[nodejs]
disabled = false
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = ' '
style = 'bold green'
not_capable_style = 'bold red'
detect_extensions = [
    'js',
    'mjs',
    'cjs',
    'ts',
]
detect_files = [
    'package.json',
    '.node-version',
    '.nvmrc',
]
detect_folders = ['node_modules']

[package]
disabled = false
format = 'is [$symbol$version]($style) '
symbol = '📦 '
style = '208 bold'
display_private = false

[python]
pyenv_version_name = false
pyenv_prefix = 'pyenv '
python_binary = [
    'python',
    'python3',
    'python2',
]
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = 'v${raw}'
style = 'yellow bold'
symbol = ' '
detect_extensions = ['py']
detect_files = [
    'requirements.txt',
    '.python-version',
    'pyproject.toml',
    'Pipfile',
    'tox.ini',
    'setup.py',
    '__init__.py',
]
detect_folders = []

[php]
disabled = false
symbol = ' '
style = '147 bold'
format = 'via [$symbol($version )]($style)'
detect_extensions = ['php']
detect_files = [
    'composer.json',
    '.php-version',
]
detect_folders = []

[ruby]
disabled = false
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = ' '
style = 'bold red'
detect_extensions = ['rb']
detect_files = [
    'Gemfile',
    '.ruby-version',
]
detect_folders = []

[rust]
disabled = false
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = ' '
style = 'bold red'
detect_extensions = ['rs']
detect_files = ['Cargo.toml']
detect_folders = []

[shell]
disabled = true
format = '$indicator '
bash_indicator = 'bsh'
fish_indicator = 'fsh'
zsh_indicator = 'zsh'
powershell_indicator = 'psh'
ion_indicator = 'ion'
elvish_indicator = 'esh'
tcsh_indicator = 'tsh'

[time]
disabled = true
format = 'at [$time]($style) '
style = 'bold yellow'
use_12hr = false
utc_time_offset = 'local'
time_range = '-'

[username]
disabled = false
format = '[$user]($style) in '
style_root = 'red bold'
style_user = 'yellow bold'
show_always = false

[vagrant]
disabled = false
format = 'via [$symbol($version )]($style)'
symbol = '⍱ '
style = 'cyan bold'
detect_extensions = []
detect_files = ['Vagrantfile']
detect_folders = []

[custom]

[status]
disabled = true

[hg_branch]
disabled = true

[aws]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[purescript]
disabled = true

[red]
disabled = true

[scala]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[zig]
disabled = true

